import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/global.css";
import "bootstrap/dist/css/bootstrap.css";
import AddBootstrap from "./addbootstrap/AddBootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cynergy Studio",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AddBootstrap />
        {children}
      </body>
    </html>
  );
}
