export const cardData = [
    {heading:"Cooper's Hawk",tags:["#softwaredevelopment","#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"image-4.png"},
    {heading:"KC Elite ecommerce store",tags:["#softwaredevelopment","#strategy"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"kcElite.png"},
    {heading:"App Store Preview",tags:["#softwaredevelopment","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"appStore.png"},
    {heading:"Disfruta",tags:["#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"image-5.png"},
    {heading:"Pauseitive",tags:["#softwaredevelopment","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"image-6.png"},
    {heading:"Ontapp",tags:["#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"image-7.png"},
    {heading:"PHILApp: Unity With a Purpose ",tags:["#softwaredevelopment","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"image-8.png"},
    {heading:"Cooper's Hawk",tags:["#strategy","#designservices"],description:"We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.",imageUrl:"image-9.png"}
]             